project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Title TK beep"
  author:
    - Sophie Wagner (sw3767)
    - Moacir P. de SÃ¡ Pereira (mpd2149)
  repo-url: https://github.com/sophiewagner7/nyc-weather
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


